### ISSUE TITLE
React useMemo style API

### ISSUE THREAD

**Issue by wholenews** [alexreardon/memoize-one#106]
It would be really nice if a React `useMemo` style API was supported, e.g. `memoize<X>(func: () => X, deps: any[]): X`.

Probably some way to achieve the same with `memoize-one` but it's not immediately clear how.

**Comment by Ayub-Begimkulov** [comment]
`useMemo` already works as `memoize-one`. It remembers only the last dependencies that you've used.

But if you want to use it in this way outside of the React component, I don't think that this is achievable nor useful. Because React associates each hook with a particular component(FiberNode). If you use `memoize` anywhere, there is no way to know if passed function's `deps` are changed unless the `func` would be referentially equal. This means that you'd have to pass your function around and have 2 imports (memoize + `func`) instead of 1.

**Comment by alexreardon** [comment]
Thanks @Ayub-Begimkulov!

React hooks need the dependency array because the function in the `useMemo` is new every time. The dependency array is how react knows whether something has changed. For normal functions we can simply use the arguments.

```ts
const add(first, second) {
  return first + second;
}

const memoizedAdd = memoizeOne(add);

memoizedAdd(1,2);
memoizedAdd(1,3); // something changed!
```

What is being suggested (i think):

```ts
const add(first, second) {
  return first + second;
}

memoizeOne(add, [1, 2]);
memoizeOne(add, [1, 3]);
```

I'm not sure if that is super ergonomic for general usage 🤔

I'll close this for now; but not closed to exploring this in the future. I don't see a huge amount of value in this as a generic API at this stage
